In [194]:
import pandas as pd

df = pd.read_csv("/home/vivek/Downloads/Ecommerce Purchases.zip", compression="zip")
print(df.head())

                                             Address    Lot AM or PM  \
0  16629 Pace Camp Apt. 448\nAlexisborough, NE 77...  46 in       PM
1  9374 Jasmine Spurs Suite 508\nSouth John, TN 8...  28 rn       PM
2                   Unit 0065 Box 5052\nDPO AP 27450  94 vE       PM
3              7780 Julia Fords\nNew Stacy, WA 45798  36 vm       PM
4  23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...  20 IE       AM

                                        Browser Info  \
0  Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...
1  Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...
2  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...
3  Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...
4  Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...

                           Company       Credit Card CC Exp Date  \
0                  Martinez-Herman  6011929061123406       02/20
1  Fletcher, Richards and Whitaker  3337758169645356       11/18
2       Simpson, Williams and Pham      675957666125       08/19
3  Williams, Marshall and Buchanan  6011578504430710       02/24
4        Brown, Watson and Andrews  6011456623207998       10/25

   CC Security Code                  CC Provider  \
0               900                 JCB 16 digit
1               561                   Mastercard
2               699                 JCB 16 digit
3               384                     Discover
4               678  Diners Club / Carte Blanche

                            Email                                     Job  \
0               pdunlap@yahoo.com  Scientist, product/process development
1              anthony41@reed.com                       Drilling engineer
2  amymiller@morales-harrison.com                Customer service manager
3     brent16@olson-robinson.info                       Drilling engineer
4     christopherwright@gmail.com                             Fine artist

        IP Address Language  Purchase Price
0  149.146.147.205       el           98.14
1     15.160.41.51       fr           70.73
2   132.207.160.22       de            0.95
3     30.250.74.19       es           78.04
4     24.140.33.94       es           77.82

In [195]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  str
 1   Lot               10000 non-null  str
 2   AM or PM          10000 non-null  str
 3   Browser Info      10000 non-null  str
 4   Company           10000 non-null  str
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  str
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  str
 9   Email             10000 non-null  str
 10  Job               10000 non-null  str
 11  IP Address        10000 non-null  str
 12  Language          10000 non-null  str
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), str(11)
memory usage: 1.1 MB

check datatypes of each columns

In [196]:
df.dtypes

Address                 str
Lot                     str
AM or PM                str
Browser Info            str
Company                 str
Credit Card           int64
CC Exp Date             str
CC Security Code      int64
CC Provider             str
Email                   str
Job                     str
IP Address              str
Language                str
Purchase Price      float64
dtype: object

check null values of datasets

In [197]:
df.isnull()

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [198]:
df.isnull().sum()

Address             0
Lot                 0
AM or PM            0
Browser Info        0
Company             0
Credit Card         0
CC Exp Date         0
CC Security Code    0
CC Provider         0
Email               0
Job                 0
IP Address          0
Language            0
Purchase Price      0
dtype: int64

In [199]:
df.shape

(10000, 14)

In [200]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='str')

In [201]:
df['Purchase Price']

0       98.14
1       70.73
2        0.95
3       78.04
4       77.82
        ...
9995    82.21
9996    25.63
9997    83.98
9998    38.84
9999    67.59
Name: Purchase Price, Length: 10000, dtype: float64

highest maximum purchase price

In [202]:
df['Purchase Price'].max()

np.float64(99.99)

In [203]:
df['Purchase Price'].min()

np.float64(0.0)

Average purchase price

In [204]:
df['Purchase Price'].mean()

np.float64(50.347302)

How many people have french 'fr' as their language

In [205]:
df['Language']

0       el
1       fr
2       de
3       es
4       es
        ..
9995    it
9996    pt
9997    el
9998    es
9999    el
Name: Language, Length: 10000, dtype: str

In [206]:
df['Language']=='fr'

0       False
1        True
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: Language, Length: 10000, dtype: bool

In [207]:
len(df[df['Language']=='fr'])

1097

job  title contains engineer

In [208]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='str')

In [209]:
df['Job']

0       Scientist, product/process development
1                            Drilling engineer
2                     Customer service manager
3                            Drilling engineer
4                                  Fine artist
                         ...
9995                                Printmaker
9996                           Energy engineer
9997                        Veterinary surgeon
9998                  Local government officer
9999                    Embryologist, clinical
Name: Job, Length: 10000, dtype: str

In [231]:
df_job=df['Job'].str.contains('engineer')
print(df_job)
sum_job=df['Job'].str.contains('engineer').sum()
print(sum_job)

0       False
1        True
2       False
3        True
4       False
        ...
9995    False
9996     True
9997    False
9998    False
9999    False
Name: Job, Length: 10000, dtype: bool
531

find email of the person with the following ip address:
132.207.160.22

In [211]:
df[df['IP Address']=="132.207.160.22"]['Email']

2    amymiller@morales-harrison.com
Name: Email, dtype: str

How many people have mastercard as their credit card provider and made a purchase above 50?

In [212]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='str')

In [213]:
df['CC Provider']

0                      JCB 16 digit
1                        Mastercard
2                      JCB 16 digit
3                          Discover
4       Diners Club / Carte Blanche
                   ...
9995                   JCB 15 digit
9996                   JCB 16 digit
9997                  VISA 16 digit
9998               American Express
9999                   JCB 15 digit
Name: CC Provider, Length: 10000, dtype: str

In [232]:
master_card=(df['CC Provider']=='Mastercard')
print(master_card)

sum(master_card)

0       False
1        True
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: CC Provider, Length: 10000, dtype: bool

816

In [215]:
len(df[(df['CC Provider']=="Mastercard") & (df['Purchase Price'] > 50)])

405

find email of the person with the following credit card number:
4664825258997302

In [216]:
df['Credit Card']

0       6011929061123406
1       3337758169645356
2           675957666125
3       6011578504430710
4       6011456623207998
              ...
9995     342945015358701
9996     210033169205009
9997    6011539787356311
9998     180003348082930
9999    4139972901927273
Name: Credit Card, Length: 10000, dtype: int64

In [217]:
df[df['Credit Card']==4664825258997302]

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
9992,"885 Allen Mountains Apt. 230\nWallhaven, LA 16995",40 vH,PM,Mozilla/5.0 (Macintosh; PPC Mac OS X 10_6_5) A...,Wells Ltd,4664825258997302,10/20,431,Discover,bberry@wright.net,Set designer,174.173.51.32,de,67.96

In [218]:
df[df['Credit Card']==4664825258997302]['Email']

9992    bberry@wright.net
Name: Email, dtype: str

How many people purchase during the AM and how many people purchase during PM

In [219]:
df['AM or PM']

0       PM
1       PM
2       PM
3       PM
4       AM
        ..
9995    PM
9996    AM
9997    AM
9998    PM
9999    AM
Name: AM or PM, Length: 10000, dtype: str

In [220]:
df['AM or PM'].value_counts()

AM or PM
PM    5068
AM    4932
Name: count, dtype: int64

how many people have a credit expire in 2020

In [221]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='str')

In [222]:
df['CC Exp Date']

0       02/20
1       11/18
2       08/19
3       02/24
4       10/25
        ...
9995    03/22
9996    07/25
9997    05/21
9998    11/17
9999    02/19
Name: CC Exp Date, Length: 10000, dtype: str

In [233]:
# 2020 wale rows filter karna
df_2020 = df['CC Exp Date'].str.endswith('/20')

print(df_2020)

total=df['CC Exp Date'].str.endswith('/20').sum()
print(total)

0        True
1       False
2       False
3       False
4       False
        ...
9995    False
9996    False
9997    False
9998    False
9999    False
Name: CC Exp Date, Length: 10000, dtype: bool
988

Top 5 most popular email provider ( eg . gmail.com, yahoo.com,etc...)

In [225]:
df.columns

Index(['Address', 'Lot', 'AM or PM', 'Browser Info', 'Company', 'Credit Card',
       'CC Exp Date', 'CC Security Code', 'CC Provider', 'Email', 'Job',
       'IP Address', 'Language', 'Purchase Price'],
      dtype='str')

In [226]:
df['Email']

0                    pdunlap@yahoo.com
1                   anthony41@reed.com
2       amymiller@morales-harrison.com
3          brent16@olson-robinson.info
4          christopherwright@gmail.com
                     ...
9995            iscott@wade-garner.com
9996                mary85@hotmail.com
9997                 tyler16@gmail.com
9998           elizabethmoore@reid.net
9999             rachelford@vaughn.com
Name: Email, Length: 10000, dtype: str

In [227]:
df[df['Email'].str.endswith('@yahoo.com')]['Email'].head(5)

0       pdunlap@yahoo.com
6      olivia04@yahoo.com
13    caitlin57@yahoo.com
14       aburns@yahoo.com
15     amanda39@yahoo.com
Name: Email, dtype: str

In [228]:
df[df['Email'].str.endswith('@gmail.com')]['Email'].head(5)

4     christopherwright@gmail.com
5               ynguyen@gmail.com
19           ruiznicole@gmail.com
22      chambersmichael@gmail.com
26               mlogan@gmail.com
Name: Email, dtype: str